# Generated by Django 5.1.4 on 2026-05-12 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employees_added', models.IntegerField(default=0)),
                ('employees_updated', models.IntegerField(default=0)),
                ('employees_flagged', models.IntegerField(default=0)),
                ('mps_added', models.IntegerField(default=0)),
                ('mps_updated', models.IntegerField(default=0)),
                ('mps_flagged', models.IntegerField(default=0)),
                ('offices_added', models.IntegerField(default=0)),
                ('offices_updated', models.IntegerField(default=0)),
                ('offices_flagged', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
