# Generated by Django 5.1.4 on 2026-05-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_prp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='employees_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
