# Generated by Django 5.1.4 on 2026-05-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('specifications', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('DISPOSED', 'Disposed')], default='IN_STOCK', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('amc_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_assets', to='locations.location')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('CPU_UNIT', 'CPU Unit'), ('RAM', 'RAM'), ('STORAGE_DRIVE', 'Storage Drive'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('specifications', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='assets.assetitem')),
            ],
            options={
                'verbose_name': 'Asset Component',
                'verbose_name_plural': 'Asset Components',
                'ordering': ['parent_asset__asset_tag', 'component_type'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('has_components', models.BooleanField(default=False)),
                ('spec_schema', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='assetitem',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assets.assettype'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['status'], name='assets_asse_status_a17246_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['is_deleted'], name='assets_asse_is_dele_5a44c2_idx'),
        ),
    ]
