# Generated by Django 5.1.4 on 2026-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcomponent',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
