# Generated by Django 5.1.4 on 2026-07-16 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_seed_spec_choices'),
        ('locations', '0004_location_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('amc_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='assets.assettype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_batches_created', to=settings.AUTH_USER_MODEL)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_asset_batches', to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_batches_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='assets.workorder')),
            ],
            options={
                'verbose_name': 'Bulk Add Batch',
                'verbose_name_plural': 'Bulk Add Batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='assetitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetbatch'),
        ),
        migrations.AddIndex(
            model_name='assetbatch',
            index=models.Index(fields=['is_deleted'], name='assets_asse_is_dele_5945e4_idx'),
        ),
    ]
