# Generated by Django 5.1.4 on 2026-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetbatch_assetitem_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcomponent',
            name='component_type',
            field=models.CharField(choices=[('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('CPU_UNIT', 'CPU Unit'), ('RAM', 'RAM'), ('STORAGE_DRIVE', 'Storage Drive'), ('SFP', 'SFP Module'), ('NIC', 'Network Card'), ('PSU', 'Power Supply'), ('BATTERY', 'Battery'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
