# Generated by Django 5.1.4 on 2026-06-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_seed_spec_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_brands', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Catalogue Brand',
                'verbose_name_plural': 'Catalogue Brands',
                'ordering': ['name'],
                'unique_together': {('sub_asset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_models', to='catalogue.catalogbrand')),
            ],
            options={
                'verbose_name': 'Catalogue Model',
                'verbose_name_plural': 'Catalogue Models',
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubAssetSpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable slug used as the storage key, e.g. ram, storage_type.', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('widget', models.CharField(choices=[('text', 'Text box'), ('number', 'Number + fixed unit'), ('units', 'Number + unit chips'), ('select', 'Dropdown'), ('toggle', 'Toggle / segmented chips')], default='text', max_length=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_fields', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Spec Field',
                'verbose_name_plural': 'Spec Fields',
                'ordering': ['order', 'id'],
                'unique_together': {('sub_asset', 'key')},
            },
        ),
    ]
