# Generated by Django 5.1.4 on 2026-08-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),  # AssetType, for applies_to
        ('catalogue', '0002_specfield_number_toggle_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(help_text='Stable key kept on the component row, e.g. ram, storage.', max_length=40, unique=True)),
                ('units', models.JSONField(blank=True, default=list)),
                ('default_unit', models.CharField(blank=True, max_length=20)),
                ('capacity_required', models.BooleanField(default=True, help_text='Tick for sized parts (RAM, Storage). Untick for a keyboard or a mouse.')),
                ('serial_required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.ManyToManyField(blank=True, help_text='Leave empty to offer this part on every Sub Asset.', related_name='component_types', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
