# Generated by Django 5.1.4 on 2026-05-12 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_assetcomponent_specifications_and_more'),
        ('assignees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Batch',
                'verbose_name_plural': 'Transfer Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InactiveHolderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inactive_alerts', to='assignees.assignee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inactive Holder Alert',
                'verbose_name_plural': 'Inactive Holder Alerts',
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['status'], name='assignments_status_a70ea7_idx'), models.Index(fields=['assignee', 'status'], name='assignments_assigne_21c63c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('holder_snapshot', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.assetitem')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assignees.assignee')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_performed', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.transferbatch')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['asset', 'returned_at'], name='assignments_asset_i_88e96d_idx'), models.Index(fields=['assignee', 'returned_at'], name='assignments_assigne_9eef18_idx')],
            },
        ),
    ]
