# Generated by Django 5.1.4 on 2026-08-23 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignees', '0002_cachedemployee_designation_bn_and_more'),
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_placement', models.JSONField(blank=True, default=dict)),
                ('new_placement', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_change_alerts', to='assignees.assignee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_change_alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Change Alert',
                'verbose_name_plural': 'Office Change Alerts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status'], name='assignments_status_9b5828_idx'), models.Index(fields=['assignee', 'status'], name='assignments_assigne_f011dc_idx')],
            },
        ),
    ]
