# Generated by Django 5.1.4 on 2026-05-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('source', models.CharField(choices=[('PRP_API', 'PRP API'), ('MANUAL', 'Manual')], default='PRP_API', max_length=10)),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.TextField(blank=True)),
                ('api_status', models.CharField(blank=True, max_length=50)),
                ('wing_id', models.CharField(blank=True, max_length=50)),
                ('wing_name_en', models.CharField(blank=True, max_length=200)),
                ('wing_name_bn', models.CharField(blank=True, max_length=200)),
                ('branch_id', models.CharField(blank=True, max_length=50)),
                ('branch_name_en', models.CharField(blank=True, max_length=200)),
                ('branch_name_bn', models.CharField(blank=True, max_length=200)),
                ('section_id', models.CharField(blank=True, max_length=50)),
                ('section_name_en', models.CharField(blank=True, max_length=200)),
                ('section_name_bn', models.CharField(blank=True, max_length=200)),
                ('unit_id', models.CharField(blank=True, max_length=50)),
                ('unit_name_en', models.CharField(blank=True, max_length=200)),
                ('unit_name_bn', models.CharField(blank=True, max_length=200)),
                ('office_id', models.CharField(blank=True, max_length=50)),
                ('office_name_en', models.CharField(blank=True, max_length=200)),
                ('office_name_bn', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_since', models.DateTimeField(blank=True, null=True)),
                ('last_seen_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached Employee',
                'verbose_name_plural': 'Cached Employees',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='CachedMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('source', models.CharField(choices=[('PRP_API', 'PRP API'), ('MANUAL', 'Manual')], default='PRP_API', max_length=10)),
                ('parliament_no', models.IntegerField(blank=True, null=True)),
                ('constituency', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.TextField(blank=True)),
                ('api_status', models.CharField(blank=True, max_length=50)),
                ('office_details_raw', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_since', models.DateTimeField(blank=True, null=True)),
                ('last_seen_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached MP',
                'verbose_name_plural': 'Cached MPs',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='CachedOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('parent_prp_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('PRP_API', 'PRP API'), ('MANUAL', 'Manual')], default='PRP_API', max_length=10)),
                ('name_en', models.CharField(max_length=300)),
                ('name_bn', models.CharField(blank=True, max_length=300)),
                ('is_abstract', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_since', models.DateTimeField(blank=True, null=True)),
                ('last_seen_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached Office',
                'verbose_name_plural': 'Cached Offices',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MP', 'MP (Member of Parliament)'), ('OFFICE', 'Office / Department'), ('LOCATION', 'Location (Storage)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignees_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_records', to='locations.location')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_records', to='assignees.cachedemployee')),
                ('mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_records', to='assignees.cachedmp')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_records', to='assignees.cachedoffice')),
            ],
            options={
                'verbose_name': 'Assignee',
                'verbose_name_plural': 'Assignees',
                'ordering': ['assignee_type'],
            },
        ),
        migrations.AddIndex(
            model_name='cachedemployee',
            index=models.Index(fields=['source', 'is_active'], name='assignees_c_source_fbaf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedemployee',
            index=models.Index(fields=['name_en'], name='assignees_c_name_en_2b5638_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedmp',
            index=models.Index(fields=['source', 'is_active'], name='assignees_c_source_9ee547_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedmp',
            index=models.Index(fields=['parliament_no'], name='assignees_c_parliam_6bd399_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedoffice',
            index=models.Index(fields=['source', 'is_active'], name='assignees_c_source_1315bc_idx'),
        ),
        migrations.AddIndex(
            model_name='assignee',
            index=models.Index(fields=['assignee_type', 'is_active'], name='assignees_a_assigne_ab8d57_idx'),
        ),
    ]
