# Generated by Django 5.1.4 on 2026-05-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedemployee',
            name='designation_bn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cachedemployee',
            name='designation_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cachedemployee',
            name='employee_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
