# Generated by Django 5.1.4 on 2026-05-12 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_assetcomponent_specifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MAINTENANCE_SENT', 'Sent to Maintenance'), ('MAINTENANCE_RETURN', 'Returned from Maintenance'), ('LOST', 'Reported Lost'), ('DAMAGED', 'Reported Damaged'), ('RECOVERED', 'Recovered (Found)'), ('REPAIRED', 'Repaired'), ('DISPOSED', 'Disposed'), ('COMPONENT_SWAP', 'Component Swap')], max_length=20)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='assets.assetitem')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_events', to='assets.assetcomponent')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lifecycle Event',
                'verbose_name_plural': 'Lifecycle Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['asset', 'occurred_at'], name='lifecycle_l_asset_i_28e20d_idx'), models.Index(fields=['event_type'], name='lifecycle_l_event_t_5af3ce_idx')],
            },
        ),
    ]
