# Generated by Django 5.1.4 on 2026-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleevent',
            name='event_type',
            field=models.CharField(choices=[('MAINTENANCE_SENT', 'Sent to Maintenance'), ('MAINTENANCE_RETURN', 'Returned from Maintenance'), ('LOST', 'Reported Lost'), ('DAMAGED', 'Reported Damaged'), ('RECOVERED', 'Recovered (Found)'), ('REPAIRED', 'Repaired'), ('DISPOSED', 'Disposed'), ('COMPONENT_SWAP', 'Component Swap'), ('COMPONENT_ADD', 'Component Added'), ('COMPONENT_REMOVE', 'Component Removed')], max_length=20),
        ),
    ]
